name: Publisher - Java - Maven
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest

    name: 'Publishing the package.'

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}